version: '3'
services:
  python:
    # image: python:3.4
    build:
      context: .
      dockerfile: docker/production/python/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=marketyproject.settings.production
      - PYTHONUNBUFFERED=1
    volumes:
      - static_files:/static_files
    ports:
      - 8000:8000
    command: gunicorn -w 4 marketyproject.wsgi -b 0.0.0.0:8000
    depends_on:
      - elasticsearch
  postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASS: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always
  nginx:
    # image: nginx
    build:
      context: .
      dockerfile: docker/production/nginx/Dockerfile
    volumes:
      - static_files:/static_files
    ports:
      - 80:80
  elasticsearch:
    image: launcher.gcr.io/google/elasticsearch2
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
          - esdata:/usr/share/elasticsearch/data
          

volumes:
  pgdata:
  esdata:
    driver: local  
  static_files: