version: '3.7'
services:
  web-dev:
    build:
      context: .
      dockerfile: docker/development/python/Dockerfile.dev
    command: python /app/manage.py runserver 0.0.0.0:8000
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - static_files:/static_files
      - media_volume:/app/media
    ports:
      - 3000:8000
    expose:
      - 8000
    environment:
      - SECRET_KEY=please_change_me
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=postgres
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
      - elasticsearch
  
  db:
    image: postgres:10.1-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/
  react-client:
    build:
      context: .
      dockerfile: docker/development/javascript/Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
  
  elasticsearch:
    image: launcher.gcr.io/google/elasticsearch2
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
          - esdata:/usr/share/elasticsearch/data
  
      

volumes:
  pgdata:
  esdata:
    driver: local
  static_files:
  media_volume: